application: duke-nus-edu-8
version: development
runtime: python27
api_version: 1
threadsafe: false

builtins:
- appstats: on

libraries:
- name: pycrypto
  version: "2.6"
- name: jinja2
  version: latest

handlers:
- url: /.*
  script: main.app